### ISSUE TITLE
Number of rows in sheet

### ISSUE THREAD

**Issue by ravloony** [akeneo/spreadsheet-parser#8]
I am writing an import script for a large (~135MB/500K rows, 1 sheet) xlsx file. I would like to have a progress bar but obviously that requires knowing the number of rows in the sheet. How can I do that with this library?

**Comment by antoineguigan** [comment]
Hi ravioony,

There is unfortunately no way to know the number of lines without parsing the whole sheet. The only way to do that would be to iterate over the sheet once to get the line count. Needless to say, this would not be really efficient for speed.

**Comment by antoineguigan** [comment]
Best way to do that would be :+1: 

    $iterator = new \CachingIterator($workbook->createIterator($index));
