### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by yiqing** [akeneo/spreadsheet-parser#9]
don't know why this happen , only get this error messages:
~~~
       PHP Warning 'yii\base\ErrorException' with message 'unlink(C:\Users\Administrato
r\AppData\Local\Temp\xlsACD3.tmp\xl\sharedStrings.xml): Permission denied'

in G:\yiqing-workspace\cxtx-web\vendor\akeneo\spreadsheet-parser\src\Xlsx\Archiv
e.php:117

Stack trace:
#0 G:\yiqing-workspace\cxtx-web\vendor\akeneo\spreadsheet-parser\src\Xlsx\Archiv
e.php(67): Akeneo\Component\SpreadsheetParser\Xlsx\Archive->deleteTemp()
~~~

seems can not delete the temp file created earlier ! I just report this things !

for temp usage i simple make the deleteTemp method return immediately . and manually delete the temp file which created by the Akeneo\Component\SpreadsheetParser\Xlsx\Archive class!

**Comment by antoineguigan** [comment]
Hi yiying,

Could you please provide the code that you are using ?

**Comment by DVendy** [comment]
What is the solution for this?

**Comment by ypat** [comment]
Hi.
I had the same message too, with the latest version ( 1.2.2 or 1.2.x-dev)
'unlink(C:\Users\Administrator\AppData\Local\Temp\xlsACD3.tmp\xl\sharedStrings.xml): Permission denied'

To reproduce this error, simply integrate the reading of excels files in a loop. The archives files badly close (they are still open at the time of deletion, which causes the warning message)

I solved the problem as follows : 

On akeneo-labs\spreadsheet-parser\src\Xlsx\Archive.php

Change the following "__destruct" function : 
-----------------------------------------------
    public function __destruct()
    {
            $this->deleteTemp();
            $this->closeArchive();
    }
-----------------------------------------------
to 
-----------------------------------------------
    public function __destruct()
    {
        register_shutdown_function(function(){
            $this->deleteTemp();
            $this->closeArchive();
        });        
    }
-----------------------------------------------
It worked on my code.
register_shutdown_function() => Php 4-5-7.

antoineguigan, can you include these changes in your next version please ?
Thanks !
